- api-users.yml
- Incluye clientes, contacto, direcciones, cuentas y parámetros
- URIs y Schema en inglés
- Documentación en español
> Versión 1.0 de la API general

- api-users.yml
/users/{user_id}/prepaid
/users/{user_id}/prepaid/issue
/users/{user_id}/prepaid/balance
/users/{user_id}/prepaid/balance/topup
/users/{user_id}/prepaid/balance/withdraw
/users/{user_id}/prepaid/reissue
/users/{user_id}/prepaid/status/lock
/users/{user_id}/prepaid/status/unlock
/users/{user_id}/prepaid/transactions
> API de prepago

- api-users.yml
Hice un cambio en el modelo de celular (De español a ingles) y agregue la funcionalidad a la api para buscar el usuario por telefon/rut/mail, también hice un cambio en las respuestas de envíe y validación de sms y mail
> Cambio modelo celular

- api-users.yml
Servicio indica si el código ingresado para validar celular no es válido (https://www.pivotaltracker.com/story/show/155432433)
> PUT /sms: Respuesta 422 si el código ingresado no es válido

- api-users.yml
- Repara issue #16
- Crea un campo `timestamps` a `Address`
> Repara issue #16

- api-users.yml
- docs/index.html
- Marca cada entidad como request o response
- Documenta las entidades que no se usan de manera idependiente en la API
- Corrige Bugs: ejemplos incompletos, celular y email heredaban de rut
> Mejoras de documentación para 0.2

- api-users.yml
Una empresa es un cliente con `rut.value >= 50000000` y con `company_data`
> Usuarios empresa & método login

- api-users.yml
- api_helpers.yml
> Api de helpers

- api-users.yml
Se eliminaron los servicios para listar
- Giros
- Comunas
- Regiones
- Bancos
> Eliminación de params de yaml

- api-users.yml
Eliminacion de find que es remplazado con query string en /users/
> Eliminacion de find

- api-prepaid.yml
Agrega información al recurso de notificaciones del procesador.
De momento el endpoint estara disponible en el api-mock que esta en Heroku
> Endpoint de notificacion

- api-users.yml
Agrega flag is_blacklisted para informar si el usuario esta en lista negra
> Agrega flag is_blacklisted

- api-bdp.yml
- Se corrige los problemas de spectacle con el Swagger.
- Se simplifica la api.
- Se eliminan datos innecesarios de la API
- Se elimina Tef de la API
- Se elimina cupon de la API
> Cambios API pasarela

- api-bdp.yml
> Correcciones

- api-bdp.yml
Se agrega el objeto user a boton de pago
> objeto-user

- api-card-payments.yml
Add batch refund and batch reversal, fix soft-descriptor
> batch refund/reversal, mod soft-descriptor

- api-users.yml
Búsqueda por tipo y fecha creacion
> Agrega endpoint para buscar tickets en freshdesk

- api-prepaid.yml
Agrega headers a las respuestas de topup, withdraw y reversas.
El header, en caso de error, incluye el tracerId.
> Agrega documentacion de headers

- api-prepaid.yml
Se agrega el detalle de cada 401 a los 4 endpoint principales.
> Agrega detalle del 401 a los 4 endpoints

- api-prepaid.yml
Agrega al topup y al retiro un detalle de errores que podria devolver tecnocom.
> Agrega nuevos errores tecnocom
